before_install:
- npm install -g bower
- bower install
language: node_js
node_js:
- '0.10'
env:
  global:
    secure: LSmHs32nmcjgp3/5hQASgIPUDF/zexvwV/XASRYCDkwJRllDZ8n8wIvHx+D1QVcotx7jSAVEKM2tcfMq/JLXVHUmNNpeG9maUMfZAHA7xFlAo5GNAG3p/rqYe3tan9Xum+Is6A71kXTVnaVyOTG5ApEyj8QUwPfHpv1ziGJu72Y=
deploy:
  skip_cleanup: true
  provider: npm
  email: matt@lonelyvegan.com
  api_key:
    secure: Ep7wUn/nAejJQRRoYa3DVqJ4vdy/2N7O4/w/dkfB6jWGSnqDLVtjx9ZrYg92ms0Ttr0FaN1r7U4Qqa7Q8/0FcMOtPwSGnguqHe+3sya/2tt8MkiKiSj5TNfyYjsr6457iIitz/K6adacqsOp9XdYKtuRJudvPXkEH4aeKNeyrbY=
  on:
    tags: true
    repo: mozilla/localForage
    branch: master
